"""The managed .gitignore block: its markers, its merge, and the write that records it.

Scaffold output — regenerated in place, never hand-owned. Entries outside the markers are
the project's and must survive every merge; unbalanced markers mean a hand edit is in
flight and are reported, not rewritten.
"""
from __future__ import annotations

from typing import Any, Optional

GITIGNORE_BEGIN = "# BEGIN ai-badger managed block — do not edit; regenerated by welcome-ai-badger"
GITIGNORE_END = "# END ai-badger managed block"
# The task tracker's SQLite database and its WAL/SHM sidecars, scoped to the task-tracking
# dir so the patterns anchor at the repo root (user-scope ~/.ai-badger is outside any repo).
# `.ai-badger.bckp/` is den-refresh's backup of `.ai-badger/` (L3-8): the backup itself
# excludes those SQLite files (refresh.py), but the whole directory is ignored too, so a
# backup taken before that fix — or any other file a future backup picks up — never shows
# up as untracked either.
GITIGNORE_ARTIFACTS = (
    ".ai-badger/task-tracking/tracking.db",
    ".ai-badger/task-tracking/*.db-wal",
    ".ai-badger/task-tracking/*.db-shm",
    ".ai-badger.bckp/",
)


def gitignore_managed_block() -> str:
    """The marker-delimited .gitignore block scaffold.py owns in the target repo."""
    return "\n".join([GITIGNORE_BEGIN, *GITIGNORE_ARTIFACTS, GITIGNORE_END]) + "\n"


def merge_gitignore(text: str) -> Optional[str]:
    """Merge the managed block into .gitignore content; None when the markers are unbalanced.

    Idempotent: an existing block is replaced in place (its interior is scaffold output, a
    hand edit there is stale), an absent one is appended after the project's entries. The
    project's entries outside the markers are never touched.
    """
    lines = text.splitlines()
    begins = [i for i, line in enumerate(lines) if line.strip() == GITIGNORE_BEGIN]
    ends = [i for i, line in enumerate(lines) if line.strip() == GITIGNORE_END]
    if bool(begins) != bool(ends) or len(begins) > 1 or len(ends) > 1:
        return None
    block = gitignore_managed_block().splitlines()
    if begins:
        return "\n".join(lines[:begins[0]] + block + lines[ends[0] + 1:]) + "\n"
    body = text if text.endswith("\n") or not text else text + "\n"
    return body + ("\n" if body.strip() else "") + gitignore_managed_block()


def write_gitignore_block(ctx: Any) -> None:
    """Merge the managed block into ``ctx.target/.gitignore``; report to ``ctx.notes``.

    A missing file is scaffolded fresh; a non-UTF-8 one is left alone and reported. Provenance
    goes to ``ctx.record_generated_config`` only for a write, so the manifest can answer
    "did ai-badger touch .gitignore?".
    """
    path = ctx.target / ".gitignore"
    try:
        text = path.read_text(encoding="utf-8") if path.exists() else ""
    except UnicodeDecodeError:
        ctx.notes.append(".gitignore is not UTF-8 text — managed block not written")
        return
    merged = merge_gitignore(text)
    if merged is None:
        ctx.notes.append(".gitignore has an unbalanced ai-badger block marker — "
                         "managed block not rewritten; fix the markers by hand")
        return
    if merged != text:
        path.write_text(merged, encoding="utf-8")
        ctx.notes.append("merged managed gitignore block (task-tracking SQLite artifacts, "
                         "den-refresh backup dir)")
        ctx.record_generated_config(path, ".gitignore")
